function DKSalaries = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DKSALARIES = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  DKSALARIES = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  DKSalaries = importfile("C:\Users\lli4\Documents\MATLAB\NBA DFS\DKSalaries.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Dec-2020 10:55:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Position", "NameID", "Name", "ID", "RosterPosition", "Salary", "GameInfo", "TeamAbbrev", "AvgPointsPerGame"];
opts.VariableTypes = ["categorical", "string", "categorical", "double", "categorical", "double", "categorical", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, "NameID", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Position", "NameID", "Name", "RosterPosition", "GameInfo", "TeamAbbrev"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["ID", "Salary", "AvgPointsPerGame"], "ThousandsSeparator", ",");

% Import the data
DKSalaries = readtable(filename, opts);

end